version: '3.7'

volumes:
  kong_data: {}
  mongodbdata: {}

networks:
  kong-net:
    external: false

services:
  camel-integration:
    image: 'moti.bc.ca/weather-canada-http'
    container_name: integration-camel-native
    environment:
      - FILE_DESTINATION=/dest/data
    volumes:
      - './.data:/dest/data'
    networks: 
      - kong-net
  moti-events:
    container_name: event_api_app
    image: moti/events-api-nodejs:v1-demo2
    build: ./events-endpoint-api
    networks: 
      - kong-net
    depends_on:
      - kong
      - mongodb
      - moti-geostore
    environment:
      - MOTI_API_MONGO_DB_HOST=mongodb
      - MOTI_API_EVENTS_PORT=8080
      - MOTI_API_GEOSTORE_HOST=moti-geostore:8080
      - MOTI_ZIPKIN_HOST=zipkin
  moti-api-catalog:
    container_name: moti_api_catalog
    image: moti/moti-api-catalog:v1-demo2
    build: ./api-catalog
    networks: 
      - kong-net
    depends_on:
      - kong
    environment:
      - KONG_HOST=http://kong:8001
    ports:
      - "8300:3000"

  moti-images:
    container_name: images_api_app
    image: moti/images-api-nodejs:v1-demo2
    build: ./images-endpoint-api
    networks: 
      - kong-net
    depends_on:
      - kong
      - mongodb
      - moti-geostore
    environment:
      - MOTI_API_MONGO_DB_HOST=mongodb
      - MOTI_API_IMAGES_PORT=8080      
      - MOTI_API_GEOSTORE_HOST=moti-geostore:8080
      - MOTI_ZIPKIN_HOST=zipkin
  moti-geostore:
    container_name: geostore_api_app
    image: moti/geostore-api-nodejs:v1-demo2
    build: ./geostore-endpoint-api
    networks: 
      - kong-net
    depends_on:
      - kong
      - mongodb
    environment:
      - MOTI_API_MONGO_DB_HOST=mongodb
      - MOTI_API_GEOSTORE_PORT=8080      
      - MOTI_ZIPKIN_HOST=zipkin
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations bootstrap
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
  kong:
    container_name: moti-api-gateway-kong.v1
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    depends_on:
      - db
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    networks:
      - kong-net
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:9444:9444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo:4.4
    container_name: moti-mongo-db
    environment:
      - MONGO_INITDB_DATABASE=event-db
      - MONGO_INITDB_ROOT_USERNAME=eventroot
      - MONGO_INITDB_ROOT_PASSWORD=eventpassword
    networks:
      - kong-net
    volumes:
      - mongodbdata:/var/lib/mongodb/data
      - ./mongodb-users.js:/docker-entrypoint-initdb.d/01-users.js:ro
      - ./mongodb-seed-data.js:/docker-entrypoint-initdb.d/02-seed-data.js:ro
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
  db:
    container_name: api_middleware_db_postgres
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    networks:
      - kong-net
    volumes:
      - kong_data:/var/lib/postgresql/data

secrets:
  kong_postgres_password:
    file: ./POSTGRES_PASSWORD