version: '3.7'

services:
  camel-integration:
    image: 'moti.bc.ca/weather-canada-http'
    container_name: integration-camel-native
    environment:
      - FILE_DESTINATION=/dest/data
    volumes:
      - './.data:/dest/data'
